In [1]:
import pandas as pd

In [48]:
df_original = pd.read_csv("../data/cmadrid_5_2025.csv", parse_dates = True, sep = ";")
df_original.head()

,provincia,municipio,estacion,magnitud,punto_muestreo,ano,mes,dia,h01,v01,...,h20,v20,h21,v21,h22,v22,h23,v23,h24,v24
0,28,102,1,1,28102001_1_38,2025,5,1,3,V,...,4,V,4,V,4,V,4,V,4,V
1,28,102,1,6,28102001_6_48,2025,5,1,"0,4",V,...,"0,4",V,"0,3",V,"0,4",V,"0,4",V,"0,4",V
2,28,102,1,7,28102001_7_8,2025,5,1,1,V,...,1,V,1,V,1,V,1,V,1,V
3,28,102,1,8,28102001_8_8,2025,5,1,2,V,...,1,V,1,V,1,V,1,V,1,V
4,28,102,1,10,28102001_10_49,2025,5,1,9,V,...,33,V,30,V,28,V,25,V,24,V

In [49]:
df_pruebas = df_original[["punto_muestreo", "ano", "mes", "dia", "h01", "v01", "h02", "v02", "h03", "v03","h04", "v04"]]
df_pruebas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 718 entries, 0 to 717
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   punto_muestreo  718 non-null    object
 1   ano             718 non-null    int64
 2   mes             718 non-null    int64
 3   dia             718 non-null    int64
 4   h01             718 non-null    object
 5   v01             718 non-null    object
 6   h02             717 non-null    object
 7   v02             718 non-null    object
 8   h03             701 non-null    object
 9   v03             718 non-null    object
 10  h04             701 non-null    object
 11  v04             718 non-null    object
dtypes: int64(3), object(9)
memory usage: 67.4+ KB

In [50]:
df_pruebas[["ano", "mes", "dia"]] = (df_pruebas[["ano", "mes", "dia"]]).astype(str)

C:\Users\marta\AppData\Local\Temp\ipykernel_17740\2820210921.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pruebas[["ano", "mes", "dia"]] = (df_pruebas[["ano", "mes", "dia"]]).astype(str)

In [51]:
df_pruebas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 718 entries, 0 to 717
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   punto_muestreo  718 non-null    object
 1   ano             718 non-null    object
 2   mes             718 non-null    object
 3   dia             718 non-null    object
 4   h01             718 non-null    object
 5   v01             718 non-null    object
 6   h02             717 non-null    object
 7   v02             718 non-null    object
 8   h03             701 non-null    object
 9   v03             718 non-null    object
 10  h04             701 non-null    object
 11  v04             718 non-null    object
dtypes: object(12)
memory usage: 67.4+ KB

In [52]:
df_pruebas["fecha"] = df_pruebas["ano"] + "-" + df_pruebas["mes"] + "-" + df_pruebas["dia"]
df_pruebas.drop(columns = ["ano", "mes", "dia"], inplace=True)
df_pruebas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 718 entries, 0 to 717
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   punto_muestreo  718 non-null    object
 1   h01             718 non-null    object
 2   v01             718 non-null    object
 3   h02             717 non-null    object
 4   v02             718 non-null    object
 5   h03             701 non-null    object
 6   v03             718 non-null    object
 7   h04             701 non-null    object
 8   v04             718 non-null    object
 9   fecha           718 non-null    object
dtypes: object(10)
memory usage: 56.2+ KB

C:\Users\marta\AppData\Local\Temp\ipykernel_17740\2063085378.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pruebas["fecha"] = df_pruebas["ano"] + "-" + df_pruebas["mes"] + "-" + df_pruebas["dia"]
C:\Users\marta\AppData\Local\Temp\ipykernel_17740\2063085378.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pruebas.drop(columns = ["ano", "mes", "dia"], inplace=True)

In [53]:
df_pruebas

     punto_muestreo  h01 v01  h02 v02  h03 v03  h04 v04     fecha
0     28102001_1_38    3   V    4   V    4   V    4   V  2025-5-1
1     28102001_6_48  0,4   V  0,3   V  0,4   V  0,4   V  2025-5-1
2      28102001_7_8    1   V    1   V    1   V    1   V  2025-5-1
3      28102001_8_8    2   V    1   V    1   V    1   V  2025-5-1
4    28102001_10_49    9   V    6   V    8   V    7   V  2025-5-1
..              ...  ...  ..  ...  ..  ...  ..  ...  ..       ...
713    28092005_7_8    3   V    3   V    3   V    2   V  2025-5-4
714    28092005_8_8    6   V    6   V    6   V    3   V  2025-5-4
715  28092005_10_49    6   V    5   V    8   V    4   V  2025-5-4
716   28092005_12_8   10   V   10   V   11   V    6   V  2025-5-4
717   28092005_14_6   60   V   59   V   56   V   59   V  2025-5-4

[718 rows x 10 columns]

In [54]:
df_pruebas_peque = df_pruebas[df_pruebas["punto_muestreo"].str.startswith("28102001")]
df_pruebas_peque

     punto_muestreo  h01 v01  h02 v02  h03 v03  h04 v04     fecha
0     28102001_1_38    3   V    4   V    4   V    4   V  2025-5-1
1     28102001_6_48  0,4   V  0,3   V  0,4   V  0,4   V  2025-5-1
2      28102001_7_8    1   V    1   V    1   V    1   V  2025-5-1
3      28102001_8_8    2   V    1   V    1   V    1   V  2025-5-1
4    28102001_10_49    9   V    6   V    8   V    7   V  2025-5-1
5     28102001_12_8    4   V    3   V    3   V    3   V  2025-5-1
6     28102001_14_6   85   V   85   V   81   V   79   V  2025-5-1
182   28102001_1_38    4   V    4   V    4   V    4   V  2025-5-2
183   28102001_6_48  0,4   V  0,4   V  0,4   V  0,4   V  2025-5-2
184    28102001_7_8    1   V    1   V    1   V    1   V  2025-5-2
185    28102001_8_8    1   V    1   V    1   V    1   V  2025-5-2
186  28102001_10_49   24   V   23   V   24   V   24   V  2025-5-2
187   28102001_12_8    3   V    3   V    3   V    3   V  2025-5-2
188   28102001_14_6   89   V   86   V   85   V   76   V  2025-5-2
364   28102001_1_38    4   V    4   V    4   V    4   V  2025-5-3
365   28102001_6_48  0,4   V  0,4   V  0,4   V  0,4   V  2025-5-3
366    28102001_7_8    1   V    1   V    1   V    1   V  2025-5-3
367    28102001_8_8    1   V    1   V    1   V    1   V  2025-5-3
368  28102001_10_49    6   V    5   V    5   V    4   V  2025-5-3
369   28102001_12_8    3   V    3   V    3   V    3   V  2025-5-3
370   28102001_14_6   62   V   62   V   65   V   65   V  2025-5-3
541   28102001_1_38    4   V    4   V    4   V    4   V  2025-5-4
542   28102001_6_48  0,4   V  0,4   V  0,4   V  0,4   V  2025-5-4
543    28102001_7_8    1   V    1   V    1   V    1   V  2025-5-4
544    28102001_8_8    1   V    1   V    1   V    1   V  2025-5-4
545  28102001_10_49    3   V    5   V    4   V    4   V  2025-5-4
546   28102001_12_8    3   V    3   V    3   V    3   V  2025-5-4
547   28102001_14_6   69   V   66   V   64   V   65   V  2025-5-4

In [55]:
def combinar_h_v(df):
    """
    Combina pares de columnas que empiezan por 'h' y 'v' en un DataFrame,
    creando nuevas columnas con los valores combinados. Además, devuelve
    una lista de las columnas creadas.

    Args:
        df (pd.DataFrame): DataFrame original.

    Returns:
        pd.DataFrame: DataFrame con columnas combinadas añadidas.
        list: Lista de nombres de las columnas creadas.
    """
    columnas_h = [col for col in df.columns if col.startswith('h')]
    columnas_v = [col for col in df.columns if col.startswith('v')]
    
    columnas_creadas = []  # Lista para almacenar nombres de las columnas creadas

    for col_h, col_v in zip(columnas_h, columnas_v):
        nueva_columna = f"{col_h}_{col_v}"  # Nombre de la nueva columna
        df[nueva_columna] = df[col_h].astype(str) + " " + df[col_v].astype(str)
        columnas_creadas.append(nueva_columna)  # Agregar el nombre de la columna a la lista
    
    return df, columnas_creadas

In [56]:
df_pruebas_peque, columnas_creadas = combinar_h_v(df_pruebas_peque)
df_pruebas_peque

C:\Users\marta\AppData\Local\Temp\ipykernel_17740\3637698816.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[nueva_columna] = df[col_h].astype(str) + " " + df[col_v].astype(str)
C:\Users\marta\AppData\Local\Temp\ipykernel_17740\3637698816.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[nueva_columna] = df[col_h].astype(str) + " " + df[col_v].astype(str)
C:\Users\marta\AppData\Local\Temp\ipykernel_17740\3637698816.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[nueva_columna] = df[col_h].astype(str) + " " + df[col_v].astype(str)
C:\Users\marta\AppData\Local\Temp\ipykernel_17740\3637698816.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[nueva_columna] = df[col_h].astype(str) + " " + df[col_v].astype(str)

,punto_muestreo,h01,v01,h02,v02,h03,v03,h04,v04,fecha,h01_v01,h02_v02,h03_v03,h04_v04
0,28102001_1_38,3,V,4,V,4,V,4,V,2025-5-1,3 V,4 V,4 V,4 V
1,28102001_6_48,"0,4",V,"0,3",V,"0,4",V,"0,4",V,2025-5-1,"0,4 V","0,3 V","0,4 V","0,4 V"
2,28102001_7_8,1,V,1,V,1,V,1,V,2025-5-1,1 V,1 V,1 V,1 V
3,28102001_8_8,2,V,1,V,1,V,1,V,2025-5-1,2 V,1 V,1 V,1 V
4,28102001_10_49,9,V,6,V,8,V,7,V,2025-5-1,9 V,6 V,8 V,7 V
5,28102001_12_8,4,V,3,V,3,V,3,V,2025-5-1,4 V,3 V,3 V,3 V
6,28102001_14_6,85,V,85,V,81,V,79,V,2025-5-1,85 V,85 V,81 V,79 V
182,28102001_1_38,4,V,4,V,4,V,4,V,2025-5-2,4 V,4 V,4 V,4 V
183,28102001_6_48,"0,4",V,"0,4",V,"0,4",V,"0,4",V,2025-5-2,"0,4 V","0,4 V","0,4 V","0,4 V"
184,28102001_7_8,1,V,1,V,1,V,1,V,2025-5-2,1 V,1 V,1 V,1 V
185,28102001_8_8,1,V,1,V,1,V,1,V,2025-5-2,1 V,1 V,1 V,1 V
186,28102001_10_49,24,V,23,V,24,V,24,V,2025-5-2,24 V,23 V,24 V,24 V
187,28102001_12_8,3,V,3,V,3,V,3,V,2025-5-2,3 V,3 V,3 V,3 V
188,28102001_14_6,89,V,86,V,85,V,76,V,2025-5-2,89 V,86 V,85 V,76 V
364,28102001_1_38,4,V,4,V,4,V,4,V,2025-5-3,4 V,4 V,4 V,4 V
365,28102001_6_48,"0,4",V,"0,4",V,"0,4",V,"0,4",V,2025-5-3,"0,4 V","0,4 V","0,4 V","0,4 V"
366,28102001_7_8,1,V,1,V,1,V,1,V,2025-5-3,1 V,1 V,1 V,1 V
367,28102001_8_8,1,V,1,V,1,V,1,V,2025-5-3,1 V,1 V,1 V,1 V
368,28102001_10_49,6,V,5,V,5,V,4,V,2025-5-3,6 V,5 V,5 V,4 V
369,28102001_12_8,3,V,3,V,3,V,3,V,2025-5-3,3 V,3 V,3 V,3 V
370,28102001_14_6,62,V,62,V,65,V,65,V,2025-5-3,62 V,62 V,65 V,65 V
541,28102001_1_38,4,V,4,V,4,V,4,V,2025-5-4,4 V,4 V,4 V,4 V
542,28102001_6_48,"0,4",V,"0,4",V,"0,4",V,"0,4",V,2025-5-4,"0,4 V","0,4 V","0,4 V","0,4 V"
543,28102001_7_8,1,V,1,V,1,V,1,V,2025-5-4,1 V,1 V,1 V,1 V
544,28102001_8_8,1,V,1,V,1,V,1,V,2025-5-4,1 V,1 V,1 V,1 V
545,28102001_10_49,3,V,5,V,4,V,4,V,2025-5-4,3 V,5 V,4 V,4 V
546,28102001_12_8,3,V,3,V,3,V,3,V,2025-5-4,3 V,3 V,3 V,3 V
547,28102001_14_6,69,V,66,V,64,V,65,V,2025-5-4,69 V,66 V,64 V,65 V

In [57]:
df_horas = df_pruebas_peque.melt(
    id_vars=["punto_muestreo", "fecha"],  # Columnas que no se transforman
    value_vars=["h01_v01", "h02_v02", "h03_v03", "h04_v04"],  # Columnas de horas que queremos transformar
    var_name="hora",  # Nombre de la nueva columna que contiene las etiquetas de hora
    value_name="valor"  # Nombre de la nueva columna que contiene los valores
)

In [58]:
df_horas.sort_values(by = ["punto_muestreo", "fecha", "hora"], inplace=True)
df_horas

     punto_muestreo     fecha     hora valor
4    28102001_10_49  2025-5-1  h01_v01   9 V
32   28102001_10_49  2025-5-1  h02_v02   6 V
60   28102001_10_49  2025-5-1  h03_v03   8 V
88   28102001_10_49  2025-5-1  h04_v04   7 V
11   28102001_10_49  2025-5-2  h01_v01  24 V
..              ...       ...      ...   ...
101    28102001_8_8  2025-5-3  h04_v04   1 V
24     28102001_8_8  2025-5-4  h01_v01   1 V
52     28102001_8_8  2025-5-4  h02_v02   1 V
80     28102001_8_8  2025-5-4  h03_v03   1 V
108    28102001_8_8  2025-5-4  h04_v04   1 V

[112 rows x 4 columns]

In [59]:
# ahora separamos la letra que acompaña al valor para crear la columna de validación y dejamos solo la hora en la columna hora
df_horas["hora"] = df_horas["hora"].str.split("_", expand = True)[0]
df_horas["validacion"] = df_horas["valor"].str.split(" ", expand = True)[1]
df_horas["valor"] = df_horas["valor"].str.split(" ", expand = True)[0]
df_horas["id_medida"] = df_horas["punto_muestreo"] + "_" + df_horas["fecha"] + "_" + df_horas["hora"] + "_" + df_horas["validacion"]
df_horas.drop(columns=["punto_muestreo", "fecha", "hora", "validacion"], inplace=True)
df_horas

    valor                      id_medida
4       9  28102001_10_49_2025-5-1_h01_V
32      6  28102001_10_49_2025-5-1_h02_V
60      8  28102001_10_49_2025-5-1_h03_V
88      7  28102001_10_49_2025-5-1_h04_V
11     24  28102001_10_49_2025-5-2_h01_V
..    ...                            ...
101     1    28102001_8_8_2025-5-3_h04_V
24      1    28102001_8_8_2025-5-4_h01_V
52      1    28102001_8_8_2025-5-4_h02_V
80      1    28102001_8_8_2025-5-4_h03_V
108     1    28102001_8_8_2025-5-4_h04_V

[112 rows x 2 columns]

In [60]:
# ahora aplicamos todo al df grande
def formato_df(df):
    # nos aseguramos de que las columnas de fecha son str
    df[["ano", "mes", "dia"]] = (df[["ano", "mes", "dia"]]).astype(str)
    # rellenamos mes y dia para que siempre tengan 2 dígitos
    df["mes"] = df["mes"].str.zfill(2)
    df["dia"] = df["dia"].str.zfill(2)
    # creamos la columna de fecha
    df["fecha"] = df["ano"] + "-" + df["mes"] + "-" + df["dia"]
    # combinamos las columnas de hora y validacion  
    df, columnas_creadas = combinar_h_v(df)
    # transformamos el df para que las columnas de hora queden en filas
    df = df.melt(
        id_vars = ["provincia", "municipio", "estacion", "magnitud", "punto_muestreo", "fecha"],  # Columnas que no se transforman
        value_vars = columnas_creadas,  # Columnas de horas que queremos transformar
        var_name = "hora",  # Nombre de la nueva columna que contiene las etiquetas de hora
        value_name = "valor"  # Nombre de la nueva columna que contiene los valores de las medidas
        )
    # ahora separamos la letra que acompaña al valor para crear la columna de validación y dejamos solo la hora en la columna hora
    df["hora"] = df["hora"].str.split("_", expand = True)[0].str.extract("(\\d+)")[0]
    # como tenemos un valor 24 para la hora y no lo admite datetime, lo sustituimos por 23:59 y añadimos un :00 en las demás horas
    df["hora"] = df["hora"].apply(lambda x: '23:59' if x == '24' else f"{str(x)}:00")
    # creamos una columna de fecha y hora con formato datetime para poder hacer operaciones con ella
    df["fecha_hora_f"] = pd.to_datetime(df["fecha"].astype(str) + " " + df["hora"].astype(str))
    # obtenemos el estado de validación de la medida a partir de la columna de valor
    df["validacion"] = df["valor"].str.split(" ", expand = True)[1]
    df["valor"] = df["valor"].str.split(" ", expand = True)[0]
    #creamos un id de la medida único para cada fila (estacion, contaminante, fecha y hora)
    df["id_medida"] = df["punto_muestreo"] + "_" + df["fecha"] + "_" + df["hora"] + "_" + df["validacion"]
    
    return df

In [61]:
df_original.head()

,provincia,municipio,estacion,magnitud,punto_muestreo,ano,mes,dia,h01,v01,...,h20,v20,h21,v21,h22,v22,h23,v23,h24,v24
0,28,102,1,1,28102001_1_38,2025,5,1,3,V,...,4,V,4,V,4,V,4,V,4,V
1,28,102,1,6,28102001_6_48,2025,5,1,"0,4",V,...,"0,4",V,"0,3",V,"0,4",V,"0,4",V,"0,4",V
2,28,102,1,7,28102001_7_8,2025,5,1,1,V,...,1,V,1,V,1,V,1,V,1,V
3,28,102,1,8,28102001_8_8,2025,5,1,2,V,...,1,V,1,V,1,V,1,V,1,V
4,28,102,1,10,28102001_10_49,2025,5,1,9,V,...,33,V,30,V,28,V,25,V,24,V

In [62]:
df_original.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 718 entries, 0 to 717
Data columns (total 56 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   provincia       718 non-null    int64
 1   municipio       718 non-null    int64
 2   estacion        718 non-null    int64
 3   magnitud        718 non-null    int64
 4   punto_muestreo  718 non-null    object
 5   ano             718 non-null    int64
 6   mes             718 non-null    int64
 7   dia             718 non-null    int64
 8   h01             718 non-null    object
 9   v01             718 non-null    object
 10  h02             717 non-null    object
 11  v02             718 non-null    object
 12  h03             701 non-null    object
 13  v03             718 non-null    object
 14  h04             701 non-null    object
 15  v04             718 non-null    object
 16  h05             703 non-null    object
 17  v05             718 non-null    object
 18  h06             702 non-null    object
 19  v06             718 non-null    object
 20  h07             702 non-null    object
 21  v07             718 non-null    object
 22  h08             703 non-null    object
 23  v08             718 non-null    object
 24  h09             711 non-null    object
 25  v09             718 non-null    object
 26  h10             711 non-null    object
 27  v10             718 non-null    object
 28  h11             710 non-null    object
 29  v11             718 non-null    object
 30  h12             711 non-null    object
 31  v12             718 non-null    object
 32  h13             710 non-null    object
 33  v13             718 non-null    object
 34  h14             709 non-null    object
 35  v14             718 non-null    object
 36  h15             711 non-null    object
 37  v15             718 non-null    object
 38  h16             711 non-null    object
 39  v16             718 non-null    object
 40  h17             711 non-null    object
 41  v17             718 non-null    object
 42  h18             712 non-null    object
 43  v18             718 non-null    object
 44  h19             710 non-null    object
 45  v19             718 non-null    object
 46  h20             711 non-null    object
 47  v20             718 non-null    object
 48  h21             713 non-null    object
 49  v21             718 non-null    object
 50  h22             712 non-null    object
 51  v22             718 non-null    object
 52  h23             713 non-null    object
 53  v23             718 non-null    object
 54  h24             713 non-null    object
 55  v24             718 non-null    object
dtypes: int64(7), object(49)
memory usage: 314.3+ KB

In [63]:
mayo2025 = formato_df(df_original)
mayo2025

,provincia,municipio,estacion,magnitud,punto_muestreo,fecha,hora,valor,fecha_hora_f,validacion,id_medida
0,28,102,1,1,28102001_1_38,2025-05-01,01:00,3,2025-05-01 01:00:00,V,28102001_1_38_2025-05-01_01:00_V
1,28,102,1,6,28102001_6_48,2025-05-01,01:00,"0,4",2025-05-01 01:00:00,V,28102001_6_48_2025-05-01_01:00_V
2,28,102,1,7,28102001_7_8,2025-05-01,01:00,1,2025-05-01 01:00:00,V,28102001_7_8_2025-05-01_01:00_V
3,28,102,1,8,28102001_8_8,2025-05-01,01:00,2,2025-05-01 01:00:00,V,28102001_8_8_2025-05-01_01:00_V
4,28,102,1,10,28102001_10_49,2025-05-01,01:00,9,2025-05-01 01:00:00,V,28102001_10_49_2025-05-01_01:00_V
...,...,...,...,...,...,...,...,...,...,...,...
17227,28,92,5,7,28092005_7_8,2025-05-04,23:59,5,2025-05-04 23:59:00,V,28092005_7_8_2025-05-04_23:59_V
17228,28,92,5,8,28092005_8_8,2025-05-04,23:59,15,2025-05-04 23:59:00,V,28092005_8_8_2025-05-04_23:59_V
17229,28,92,5,10,28092005_10_49,2025-05-04,23:59,2,2025-05-04 23:59:00,V,28092005_10_49_2025-05-04_23:59_V
17230,28,92,5,12,28092005_12_8,2025-05-04,23:59,22,2025-05-04 23:59:00,V,28092005_12_8_2025-05-04_23:59_V
17231,28,92,5,14,28092005_14_6,2025-05-04,23:59,48,2025-05-04 23:59:00,V,28092005_14_6_2025-05-04_23:59_V

In [64]:
prueba = mayo2025[mayo2025["fecha"] == "2025-05-01"]
prueba

,provincia,municipio,estacion,magnitud,punto_muestreo,fecha,hora,valor,fecha_hora_f,validacion,id_medida
0,28,102,1,1,28102001_1_38,2025-05-01,01:00,3,2025-05-01 01:00:00,V,28102001_1_38_2025-05-01_01:00_V
1,28,102,1,6,28102001_6_48,2025-05-01,01:00,"0,4",2025-05-01 01:00:00,V,28102001_6_48_2025-05-01_01:00_V
2,28,102,1,7,28102001_7_8,2025-05-01,01:00,1,2025-05-01 01:00:00,V,28102001_7_8_2025-05-01_01:00_V
3,28,102,1,8,28102001_8_8,2025-05-01,01:00,2,2025-05-01 01:00:00,V,28102001_8_8_2025-05-01_01:00_V
4,28,102,1,10,28102001_10_49,2025-05-01,01:00,9,2025-05-01 01:00:00,V,28102001_10_49_2025-05-01_01:00_V
...,...,...,...,...,...,...,...,...,...,...,...
16691,28,92,5,7,28092005_7_8,2025-05-01,23:59,2,2025-05-01 23:59:00,V,28092005_7_8_2025-05-01_23:59_V
16692,28,92,5,8,28092005_8_8,2025-05-01,23:59,11,2025-05-01 23:59:00,V,28092005_8_8_2025-05-01_23:59_V
16693,28,92,5,10,28092005_10_49,2025-05-01,23:59,24,2025-05-01 23:59:00,V,28092005_10_49_2025-05-01_23:59_V
16694,28,92,5,12,28092005_12_8,2025-05-01,23:59,14,2025-05-01 23:59:00,V,28092005_12_8_2025-05-01_23:59_V
16695,28,92,5,14,28092005_14_6,2025-05-01,23:59,77,2025-05-01 23:59:00,V,28092005_14_6_2025-05-01_23:59_V

In [67]:
mayo2025.loc[mayo2025["fecha"] == "2025-05-01", "fecha_hora_f"].unique()

<DatetimeArray>
['2025-05-01 01:00:00', '2025-05-01 02:00:00', '2025-05-01 03:00:00',
 '2025-05-01 04:00:00', '2025-05-01 05:00:00', '2025-05-01 06:00:00',
 '2025-05-01 07:00:00', '2025-05-01 08:00:00', '2025-05-01 09:00:00',
 '2025-05-01 10:00:00', '2025-05-01 11:00:00', '2025-05-01 12:00:00',
 '2025-05-01 13:00:00', '2025-05-01 14:00:00', '2025-05-01 15:00:00',
 '2025-05-01 16:00:00', '2025-05-01 17:00:00', '2025-05-01 18:00:00',
 '2025-05-01 19:00:00', '2025-05-01 20:00:00', '2025-05-01 21:00:00',
 '2025-05-01 22:00:00', '2025-05-01 23:00:00', '2025-05-01 23:59:00']
Length: 24, dtype: datetime64[ns]

In [69]:
df_madrid2005 = pd.read_csv("../datos/madrid_2005.csv", parse_dates = True, sep = ";")
df_madrid2005.head()

,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANO,MES,DIA,H01,V01,H02,...,H20,V20,H21,V21,H22,V22,H23,V23,H24,V24
0,79,4,1,28079004_1_38,2005,4,1,13.0,V,12.0,...,9.0,V,9.0,V,9.0,V,9.0,V,8.0,V
1,79,4,1,28079004_1_38,2005,4,2,8.0,V,7.0,...,7.0,V,8.0,V,7.0,V,7.0,V,8.0,V
2,79,4,1,28079004_1_38,2005,4,3,7.0,V,8.0,...,7.0,V,8.0,V,8.0,V,8.0,V,9.0,V
3,79,4,1,28079004_1_38,2005,4,4,8.0,V,7.0,...,9.0,V,9.0,V,9.0,V,11.0,V,12.0,V
4,79,4,1,28079004_1_38,2005,4,5,12.0,V,12.0,...,7.0,V,8.0,V,10.0,V,13.0,V,15.0,V

In [70]:
madrid2005 = formato_df(df_madrid2005)
madrid2005

KeyError: "None of [Index(['ano', 'mes', 'dia'], dtype='object')] are in the [columns]"

In [2]:
import os
import pandas as pd

In [17]:
def unir_archivos(carpeta_entrada, patron_nombre, carpeta_salida, nombre_salida):
    """
    Une los archivos de una carpera según el nombre dado y los guarda como un único csv en la carpeta de salida

    Parámetros:
        carpeta_entrada (str): ruta de la carpeta donde se encuentran los archivos que queremos unir.
        patron_nombre (str): patrón de nombre de los archivos a unir
        carpeta_salida (str): ruta de la carpeta donde se guardan los archivos unidos.
        nombre_salida (str): nombre del archivo de salida (sin extensión).

    Retorna:
        archivos: Lista con los nombres de los archivos unidos.
    """
    carpeta = carpeta_entrada
    archivos = [archivo for archivo in os.listdir(carpeta) if patron_nombre.lower() in archivo.lower()]
    df_lista = [pd.read_csv(os.path.join(carpeta, archivo), sep=";", parse_dates = True, encoding="latin1") for archivo in archivos]
    print (archivos)
    df_unido = pd.concat(df_lista, ignore_index=True)
    df_unido.to_csv(f"{carpeta_salida}/{nombre_salida}.csv", index=False)
    print(f"archivo {nombre_salida}.csv creado en {carpeta_salida}")

In [18]:
unir_archivos("../data", "cmadrid_20", "../data", "cmadrid")

C:\Users\marta\AppData\Local\Temp\ipykernel_4124\3111606863.py:16: DtypeWarning: Columns (8,54) have mixed types. Specify dtype option on import or set low_memory=False.
  df_lista = [pd.read_csv(os.path.join(carpeta, archivo), sep=";", parse_dates = True, encoding="latin1") for archivo in archivos]

['cmadrid_2005.CSV', 'cmadrid_2006.CSV', 'cmadrid_2007.CSV', 'cmadrid_2008.CSV', 'cmadrid_2009.CSV', 'cmadrid_2010.CSV', 'cmadrid_2011.CSV', 'cmadrid_2012.CSV', 'cmadrid_2013.CSV', 'cmadrid_2014.CSV', 'cmadrid_2015.CSV', 'cmadrid_2016.CSV', 'cmadrid_2017.CSV', 'cmadrid_2018.CSV', 'cmadrid_2019.CSV', 'cmadrid_2020.CSV', 'cmadrid_2021.CSV', 'cmadrid_2022.CSV', 'cmadrid_2023.CSV', 'cmadrid_2024.CSV', 'cmadrid_2025-05-01.csv', 'cmadrid_2025-05-05.csv', 'cmadrid_2025.CSV']
archivo cmadrid.csv creado en ../data

In [8]:
df_cmadrid = pd.read_csv("../data/cmadrid.csv", parse_dates = True)

In [9]:
df_cmadrid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1054914 entries, 0 to 1054913
Data columns (total 56 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   provincia       1054914 non-null  int64
 1   municipio       1054914 non-null  int64
 2   estacion        1054914 non-null  int64
 3   magnitud        1054914 non-null  int64
 4   punto_muestreo  1054914 non-null  object
 5   ano             1054914 non-null  int64
 6   mes             1054914 non-null  int64
 7   dia             1054914 non-null  int64
 8   h01             996368 non-null   object
 9   v01             1054914 non-null  object
 10  h02             996285 non-null   object
 11  v02             1054914 non-null  object
 12  h03             995518 non-null   object
 13  v03             1054914 non-null  object
 14  h04             995957 non-null   object
 15  v04             1054914 non-null  object
 16  h05             995715 non-null   object
 17  v05             1054914 non-null  object
 18  h06             991133 non-null   object
 19  v06             1054914 non-null  object
 20  h07             983390 non-null   object
 21  v07             1054914 non-null  object
 22  h08             976064 non-null   object
 23  v08             1054914 non-null  object
 24  h09             969758 non-null   object
 25  v09             1054914 non-null  object
 26  h10             966064 non-null   object
 27  v10             1054914 non-null  object
 28  h11             965043 non-null   object
 29  v11             1054914 non-null  object
 30  h12             967723 non-null   object
 31  v12             1054914 non-null  object
 32  h13             975314 non-null   object
 33  v13             1054914 non-null  object
 34  h14             983697 non-null   object
 35  v14             1054914 non-null  object
 36  h15             987088 non-null   object
 37  v15             1054914 non-null  object
 38  h16             988778 non-null   object
 39  v16             1054914 non-null  object
 40  h17             992134 non-null   object
 41  v17             1054914 non-null  object
 42  h18             994880 non-null   object
 43  v18             1054914 non-null  object
 44  h19             995655 non-null   object
 45  v19             1054914 non-null  object
 46  h20             996072 non-null   object
 47  v20             1054914 non-null  object
 48  h21             996227 non-null   object
 49  v21             1054914 non-null  object
 50  h22             992604 non-null   object
 51  v22             1054914 non-null  object
 52  h23             996213 non-null   object
 53  v23             1054914 non-null  object
 54  h24             996063 non-null   object
 55  v24             1054914 non-null  object
dtypes: int64(7), object(49)
memory usage: 450.7+ MB

In [5]:
unir_archivos("../datos", "madrid_20", "../datos", "cmadrid")

['madrid_2001.csv', 'madrid_2002.csv', 'madrid_2003.csv', 'madrid_2004.csv', 'madrid_2005.csv', 'madrid_2006.csv', 'madrid_2007.csv', 'madrid_2008.csv', 'madrid_2009.csv', 'madrid_2010.csv', 'madrid_2011.csv', 'madrid_2012.csv', 'madrid_2013.csv', 'madrid_2014.csv', 'madrid_2015.csv', 'madrid_2016.csv', 'madrid_2017.csv', 'madrid_2018.csv', 'madrid_2019.csv', 'madrid_2020.csv', 'madrid_2021.csv', 'madrid_2022.csv', 'madrid_2023.csv', 'madrid_2024.csv', 'madrid_2025-05-01.csv', 'madrid_2025-05-02.csv', 'madrid_2025-05-05.csv', 'madrid_2025.csv']
archivo cmadrid.csv creado en ../datos

In [ ]:
# cargar todos los csv de una carpeta
import os
import pandas as pd
carpeta = "../data"
archivos = [archivo for archivo in os.listdir(carpeta) if archivo.lower().startswith("cmadrid_20")]
df_lista = [pd.read_csv(os.path.join(carpeta, archivo), sep=";", parse_dates = True, encoding="latin1") for archivo in archivos]

C:\Users\marta\AppData\Local\Temp\ipykernel_17740\3541786353.py:6: DtypeWarning: Columns (8,54) have mixed types. Specify dtype option on import or set low_memory=False.
  df_lista = [pd.read_csv(os.path.join(carpeta, archivo), sep=";", parse_dates = True, encoding="latin1") for archivo in archivos]

In [75]:
archivos

['cmadrid_2005.CSV',
 'cmadrid_2006.CSV',
 'cmadrid_2007.CSV',
 'cmadrid_2008.CSV',
 'cmadrid_2009.CSV',
 'cmadrid_2010.CSV',
 'cmadrid_2011.CSV',
 'cmadrid_2012.CSV',
 'cmadrid_2013.CSV',
 'cmadrid_2014.CSV',
 'cmadrid_2015.CSV',
 'cmadrid_2016.CSV',
 'cmadrid_2017.CSV',
 'cmadrid_2018.CSV',
 'cmadrid_2019.CSV',
 'cmadrid_2020.CSV',
 'cmadrid_2021.CSV',
 'cmadrid_2022.CSV',
 'cmadrid_2023.CSV',
 'cmadrid_2024.CSV',
 'cmadrid_2025-05-01.csv',
 'cmadrid_2025-05-05.csv',
 'cmadrid_2025.CSV']

In [72]:
df_cmadrid = pd.concat(df_lista, ignore_index=True)
df_cmadrid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1054914 entries, 0 to 1054913
Data columns (total 56 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   provincia       1054914 non-null  int64
 1   municipio       1054914 non-null  int64
 2   estacion        1054914 non-null  int64
 3   magnitud        1054914 non-null  int64
 4   punto_muestreo  1054914 non-null  object
 5   ano             1054914 non-null  int64
 6   mes             1054914 non-null  int64
 7   dia             1054914 non-null  int64
 8   h01             996368 non-null   object
 9   v01             1054914 non-null  object
 10  h02             996285 non-null   object
 11  v02             1054914 non-null  object
 12  h03             995518 non-null   object
 13  v03             1054914 non-null  object
 14  h04             995957 non-null   object
 15  v04             1054914 non-null  object
 16  h05             995715 non-null   object
 17  v05             1054914 non-null  object
 18  h06             991133 non-null   object
 19  v06             1054914 non-null  object
 20  h07             983390 non-null   object
 21  v07             1054914 non-null  object
 22  h08             976064 non-null   object
 23  v08             1054914 non-null  object
 24  h09             969758 non-null   object
 25  v09             1054914 non-null  object
 26  h10             966064 non-null   object
 27  v10             1054914 non-null  object
 28  h11             965043 non-null   object
 29  v11             1054914 non-null  object
 30  h12             967723 non-null   object
 31  v12             1054914 non-null  object
 32  h13             975314 non-null   object
 33  v13             1054914 non-null  object
 34  h14             983697 non-null   object
 35  v14             1054914 non-null  object
 36  h15             987088 non-null   object
 37  v15             1054914 non-null  object
 38  h16             988778 non-null   object
 39  v16             1054914 non-null  object
 40  h17             992134 non-null   object
 41  v17             1054914 non-null  object
 42  h18             994880 non-null   object
 43  v18             1054914 non-null  object
 44  h19             995655 non-null   object
 45  v19             1054914 non-null  object
 46  h20             996072 non-null   object
 47  v20             1054914 non-null  object
 48  h21             996227 non-null   object
 49  v21             1054914 non-null  object
 50  h22             992604 non-null   object
 51  v22             1054914 non-null  object
 52  h23             996213 non-null   object
 53  v23             1054914 non-null  object
 54  h24             996063 non-null   object
 55  v24             1054914 non-null  object
dtypes: int64(7), object(49)
memory usage: 450.7+ MB

In [73]:
df_cmadrid.to_csv(f"{carpeta}/cmadrid.csv", index=False)

In [77]:
# cargar todos los csv de una carpeta
import os
import pandas as pd
carpeta = "../datos"
archivos = [archivo for archivo in os.listdir(carpeta) if archivo.lower().startswith("madrid_20")]
df_lista = [pd.read_csv(os.path.join(carpeta, archivo), sep=";", parse_dates = True, encoding="latin1") for archivo in archivos]
df_madrid = pd.concat(df_lista, ignore_index=True)
df_madrid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1068865 entries, 0 to 1068864
Data columns (total 56 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   MUNICIPIO       1068865 non-null  int64
 1   ESTACION        1068865 non-null  int64
 2   MAGNITUD        1068865 non-null  int64
 3   PUNTO_MUESTREO  1068865 non-null  object
 4   ANO             1068865 non-null  int64
 5   MES             1068865 non-null  int64
 6   DIA             1068865 non-null  int64
 7   H01             1068865 non-null  float64
 8   V01             1068865 non-null  object
 9   H02             1068865 non-null  float64
 10  V02             1068865 non-null  object
 11  H03             1068865 non-null  float64
 12  V03             1068865 non-null  object
 13  H04             1068865 non-null  float64
 14  V04             1068865 non-null  object
 15  H05             1068865 non-null  float64
 16  V05             1068865 non-null  object
 17  H06             1068865 non-null  float64
 18  V06             1068865 non-null  object
 19  H07             1068865 non-null  float64
 20  V07             1068865 non-null  object
 21  H08             1068865 non-null  float64
 22  V08             1068865 non-null  object
 23  H09             1068865 non-null  float64
 24  V09             1068865 non-null  object
 25  H10             1068865 non-null  float64
 26  V10             1068865 non-null  object
 27  H11             1068865 non-null  float64
 28  V11             1068865 non-null  object
 29  H12             1068865 non-null  float64
 30  V12             1068865 non-null  object
 31  H13             1068865 non-null  float64
 32  V13             1068865 non-null  object
 33  H14             1068865 non-null  float64
 34  V14             1068865 non-null  object
 35  H15             1068865 non-null  float64
 36  V15             1068865 non-null  object
 37  H16             1068865 non-null  float64
 38  V16             1068865 non-null  object
 39  H17             1068865 non-null  float64
 40  V17             1068865 non-null  object
 41  H18             1068865 non-null  float64
 42  V18             1068865 non-null  object
 43  H19             1068865 non-null  float64
 44  V19             1068865 non-null  object
 45  H20             1068865 non-null  float64
 46  V20             1068865 non-null  object
 47  H21             1068865 non-null  float64
 48  V21             1068865 non-null  object
 49  H22             1068865 non-null  float64
 50  V22             1068865 non-null  object
 51  H23             1068865 non-null  float64
 52  V23             1068865 non-null  object
 53  H24             1068865 non-null  float64
 54  V24             1068865 non-null  object
 55  ï»¿PROVINCIA    3144 non-null     float64
dtypes: float64(25), int64(6), object(25)
memory usage: 456.7+ MB

In [78]:
archivos

['madrid_2001.csv',
 'madrid_2002.csv',
 'madrid_2003.csv',
 'madrid_2004.csv',
 'madrid_2005.csv',
 'madrid_2006.csv',
 'madrid_2007.csv',
 'madrid_2008.csv',
 'madrid_2009.csv',
 'madrid_2010.csv',
 'madrid_2011.csv',
 'madrid_2012.csv',
 'madrid_2013.csv',
 'madrid_2014.csv',
 'madrid_2015.csv',
 'madrid_2016.csv',
 'madrid_2017.csv',
 'madrid_2018.csv',
 'madrid_2019.csv',
 'madrid_2020.csv',
 'madrid_2021.csv',
 'madrid_2022.csv',
 'madrid_2023.csv',
 'madrid_2024.csv',
 'madrid_2025-05-01.csv',
 'madrid_2025-05-02.csv',
 'madrid_2025-05-05.csv',
 'madrid_2025.csv']

In [79]:
df_madrid.to_csv(f"{carpeta}/madrid.csv", index=False)

In [ ]:
df_filtrado = df_madrid[df_madrid["ï»¿PROVINCIA"].notna()]
df_filtrado["ANO"].unique()

array([2025])

In [4]:
df_madrid = pd.read_csv("data/transformed/madrid.csv")
df_madrid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1068865 entries, 0 to 1068864
Data columns (total 56 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   MUNICIPIO       1068865 non-null  int64
 1   ESTACION        1068865 non-null  int64
 2   MAGNITUD        1068865 non-null  int64
 3   PUNTO_MUESTREO  1068865 non-null  object
 4   ANO             1068865 non-null  int64
 5   MES             1068865 non-null  int64
 6   DIA             1068865 non-null  int64
 7   H01             1068865 non-null  float64
 8   V01             1068865 non-null  object
 9   H02             1068865 non-null  float64
 10  V02             1068865 non-null  object
 11  H03             1068865 non-null  float64
 12  V03             1068865 non-null  object
 13  H04             1068865 non-null  float64
 14  V04             1068865 non-null  object
 15  H05             1068865 non-null  float64
 16  V05             1068865 non-null  object
 17  H06             1068865 non-null  float64
 18  V06             1068865 non-null  object
 19  H07             1068865 non-null  float64
 20  V07             1068865 non-null  object
 21  H08             1068865 non-null  float64
 22  V08             1068865 non-null  object
 23  H09             1068865 non-null  float64
 24  V09             1068865 non-null  object
 25  H10             1068865 non-null  float64
 26  V10             1068865 non-null  object
 27  H11             1068865 non-null  float64
 28  V11             1068865 non-null  object
 29  H12             1068865 non-null  float64
 30  V12             1068865 non-null  object
 31  H13             1068865 non-null  float64
 32  V13             1068865 non-null  object
 33  H14             1068865 non-null  float64
 34  V14             1068865 non-null  object
 35  H15             1068865 non-null  float64
 36  V15             1068865 non-null  object
 37  H16             1068865 non-null  float64
 38  V16             1068865 non-null  object
 39  H17             1068865 non-null  float64
 40  V17             1068865 non-null  object
 41  H18             1068865 non-null  float64
 42  V18             1068865 non-null  object
 43  H19             1068865 non-null  float64
 44  V19             1068865 non-null  object
 45  H20             1068865 non-null  float64
 46  V20             1068865 non-null  object
 47  H21             1068865 non-null  float64
 48  V21             1068865 non-null  object
 49  H22             1068865 non-null  float64
 50  V22             1068865 non-null  object
 51  H23             1068865 non-null  float64
 52  V23             1068865 non-null  object
 53  H24             1068865 non-null  float64
 54  V24             1068865 non-null  object
 55  ï»¿PROVINCIA    3144 non-null     float64
dtypes: float64(25), int64(6), object(25)
memory usage: 456.7+ MB

In [5]:
df_madrid.duplicated().sum()

np.int64(1307)

In [6]:
df_madrid.drop_duplicates(inplace=True)
df_madrid.duplicated().sum()

np.int64(0)

In [7]:
df_madrid = df_madrid.drop('ï»¿PROVINCIA', axis=1)
df_madrid.columns = df_madrid.columns.str.lower()
df_madrid.head(15)

,municipio,estacion,magnitud,punto_muestreo,ano,mes,dia,h01,v01,h02,...,h20,v20,h21,v21,h22,v22,h23,v23,h24,v24
0,79,4,1,28079004_1_38,2001,4,1,20.0,V,28.0,...,9.0,V,11.0,V,18.0,V,27.0,V,34.0,V
1,79,4,1,28079004_1_38,2001,4,2,17.0,V,22.0,...,12.0,V,14.0,V,15.0,V,13.0,V,11.0,V
2,79,4,1,28079004_1_38,2001,4,3,11.0,V,10.0,...,9.0,V,10.0,V,11.0,V,10.0,V,9.0,V
3,79,4,1,28079004_1_38,2001,4,4,8.0,V,8.0,...,10.0,V,10.0,V,10.0,V,9.0,V,8.0,V
4,79,4,1,28079004_1_38,2001,4,5,8.0,V,8.0,...,9.0,V,9.0,V,11.0,V,13.0,V,14.0,V
5,79,4,1,28079004_1_38,2001,4,6,15.0,V,17.0,...,14.0,V,13.0,V,13.0,V,12.0,V,12.0,V
6,79,4,1,28079004_1_38,2001,4,7,10.0,V,9.0,...,11.0,V,10.0,V,11.0,V,11.0,V,9.0,V
7,79,4,1,28079004_1_38,2001,4,8,8.0,V,7.0,...,10.0,V,12.0,V,15.0,V,14.0,V,11.0,V
8,79,4,1,28079004_1_38,2001,4,9,10.0,V,9.0,...,10.0,V,15.0,V,17.0,V,20.0,V,23.0,V
9,79,4,1,28079004_1_38,2001,4,10,25.0,V,28.0,...,10.0,V,10.0,V,11.0,V,11.0,V,11.0,V
10,79,4,1,28079004_1_38,2001,4,11,23.0,V,17.0,...,9.0,V,10.0,V,11.0,V,10.0,V,8.0,V
11,79,4,1,28079004_1_38,2001,4,12,7.0,V,7.0,...,9.0,V,12.0,V,12.0,V,10.0,V,8.0,V
12,79,4,1,28079004_1_38,2001,4,13,9.0,V,8.0,...,8.0,V,9.0,V,9.0,V,9.0,V,7.0,V
13,79,4,1,28079004_1_38,2001,4,14,8.0,V,7.0,...,9.0,V,10.0,V,13.0,V,13.0,V,10.0,V
14,79,4,1,28079004_1_38,2001,4,15,9.0,V,13.0,...,8.0,V,10.0,V,14.0,V,19.0,V,20.0,V

In [8]:
df_madrid.insert(0, "provincia", 28)

In [9]:
df_madrid.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1067558 entries, 0 to 1068864
Data columns (total 56 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   provincia       1067558 non-null  int64
 1   municipio       1067558 non-null  int64
 2   estacion        1067558 non-null  int64
 3   magnitud        1067558 non-null  int64
 4   punto_muestreo  1067558 non-null  object
 5   ano             1067558 non-null  int64
 6   mes             1067558 non-null  int64
 7   dia             1067558 non-null  int64
 8   h01             1067558 non-null  float64
 9   v01             1067558 non-null  object
 10  h02             1067558 non-null  float64
 11  v02             1067558 non-null  object
 12  h03             1067558 non-null  float64
 13  v03             1067558 non-null  object
 14  h04             1067558 non-null  float64
 15  v04             1067558 non-null  object
 16  h05             1067558 non-null  float64
 17  v05             1067558 non-null  object
 18  h06             1067558 non-null  float64
 19  v06             1067558 non-null  object
 20  h07             1067558 non-null  float64
 21  v07             1067558 non-null  object
 22  h08             1067558 non-null  float64
 23  v08             1067558 non-null  object
 24  h09             1067558 non-null  float64
 25  v09             1067558 non-null  object
 26  h10             1067558 non-null  float64
 27  v10             1067558 non-null  object
 28  h11             1067558 non-null  float64
 29  v11             1067558 non-null  object
 30  h12             1067558 non-null  float64
 31  v12             1067558 non-null  object
 32  h13             1067558 non-null  float64
 33  v13             1067558 non-null  object
 34  h14             1067558 non-null  float64
 35  v14             1067558 non-null  object
 36  h15             1067558 non-null  float64
 37  v15             1067558 non-null  object
 38  h16             1067558 non-null  float64
 39  v16             1067558 non-null  object
 40  h17             1067558 non-null  float64
 41  v17             1067558 non-null  object
 42  h18             1067558 non-null  float64
 43  v18             1067558 non-null  object
 44  h19             1067558 non-null  float64
 45  v19             1067558 non-null  object
 46  h20             1067558 non-null  float64
 47  v20             1067558 non-null  object
 48  h21             1067558 non-null  float64
 49  v21             1067558 non-null  object
 50  h22             1067558 non-null  float64
 51  v22             1067558 non-null  object
 52  h23             1067558 non-null  float64
 53  v23             1067558 non-null  object
 54  h24             1067558 non-null  float64
 55  v24             1067558 non-null  object
dtypes: float64(24), int64(7), object(25)
memory usage: 464.3+ MB

In [10]:
df_cmadrid = pd.read_csv("data/transformed/cmadrid.csv")
df_cmadrid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1054914 entries, 0 to 1054913
Data columns (total 56 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   provincia       1054914 non-null  int64
 1   municipio       1054914 non-null  int64
 2   estacion        1054914 non-null  int64
 3   magnitud        1054914 non-null  int64
 4   punto_muestreo  1054914 non-null  object
 5   ano             1054914 non-null  int64
 6   mes             1054914 non-null  int64
 7   dia             1054914 non-null  int64
 8   h01             996368 non-null   object
 9   v01             1054914 non-null  object
 10  h02             996285 non-null   object
 11  v02             1054914 non-null  object
 12  h03             995518 non-null   object
 13  v03             1054914 non-null  object
 14  h04             995957 non-null   object
 15  v04             1054914 non-null  object
 16  h05             995715 non-null   object
 17  v05             1054914 non-null  object
 18  h06             991133 non-null   object
 19  v06             1054914 non-null  object
 20  h07             983390 non-null   object
 21  v07             1054914 non-null  object
 22  h08             976064 non-null   object
 23  v08             1054914 non-null  object
 24  h09             969758 non-null   object
 25  v09             1054914 non-null  object
 26  h10             966064 non-null   object
 27  v10             1054914 non-null  object
 28  h11             965043 non-null   object
 29  v11             1054914 non-null  object
 30  h12             967723 non-null   object
 31  v12             1054914 non-null  object
 32  h13             975314 non-null   object
 33  v13             1054914 non-null  object
 34  h14             983697 non-null   object
 35  v14             1054914 non-null  object
 36  h15             987088 non-null   object
 37  v15             1054914 non-null  object
 38  h16             988778 non-null   object
 39  v16             1054914 non-null  object
 40  h17             992134 non-null   object
 41  v17             1054914 non-null  object
 42  h18             994880 non-null   object
 43  v18             1054914 non-null  object
 44  h19             995655 non-null   object
 45  v19             1054914 non-null  object
 46  h20             996072 non-null   object
 47  v20             1054914 non-null  object
 48  h21             996227 non-null   object
 49  v21             1054914 non-null  object
 50  h22             992604 non-null   object
 51  v22             1054914 non-null  object
 52  h23             996213 non-null   object
 53  v23             1054914 non-null  object
 54  h24             996063 non-null   object
 55  v24             1054914 non-null  object
dtypes: int64(7), object(49)
memory usage: 450.7+ MB

In [11]:
df_madrid.columns == df_cmadrid.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [12]:
df_medidas = pd.concat([df_madrid, df_cmadrid], ignore_index=True)
df_medidas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2122472 entries, 0 to 2122471
Data columns (total 56 columns):
 #   Column          Dtype
---  ------          -----
 0   provincia       int64
 1   municipio       int64
 2   estacion        int64
 3   magnitud        int64
 4   punto_muestreo  object
 5   ano             int64
 6   mes             int64
 7   dia             int64
 8   h01             object
 9   v01             object
 10  h02             object
 11  v02             object
 12  h03             object
 13  v03             object
 14  h04             object
 15  v04             object
 16  h05             object
 17  v05             object
 18  h06             object
 19  v06             object
 20  h07             object
 21  v07             object
 22  h08             object
 23  v08             object
 24  h09             object
 25  v09             object
 26  h10             object
 27  v10             object
 28  h11             object
 29  v11             object
 30  h12             object
 31  v12             object
 32  h13             object
 33  v13             object
 34  h14             object
 35  v14             object
 36  h15             object
 37  v15             object
 38  h16             object
 39  v16             object
 40  h17             object
 41  v17             object
 42  h18             object
 43  v18             object
 44  h19             object
 45  v19             object
 46  h20             object
 47  v20             object
 48  h21             object
 49  v21             object
 50  h22             object
 51  v22             object
 52  h23             object
 53  v23             object
 54  h24             object
 55  v24             object
dtypes: int64(7), object(49)
memory usage: 906.8+ MB

In [27]:
import sys
print(sys.path)

['c:\\Users\\marta\\AppData\\Local\\Programs\\Python\\Python313\\python313.zip', 'c:\\Users\\marta\\AppData\\Local\\Programs\\Python\\Python313\\DLLs', 'c:\\Users\\marta\\AppData\\Local\\Programs\\Python\\Python313\\Lib', 'c:\\Users\\marta\\AppData\\Local\\Programs\\Python\\Python313', '', 'C:\\Users\\marta\\AppData\\Roaming\\Python\\Python313\\site-packages', 'C:\\Users\\marta\\AppData\\Roaming\\Python\\Python313\\site-packages\\win32', 'C:\\Users\\marta\\AppData\\Roaming\\Python\\Python313\\site-packages\\win32\\lib', 'C:\\Users\\marta\\AppData\\Roaming\\Python\\Python313\\site-packages\\Pythonwin', 'c:\\Users\\marta\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages', 'c:\\Users\\marta\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\setuptools\\_vendor']

In [29]:
import sys
sys.path.append("../src")

In [13]:
from src import funciones_transform as ft 
ft.combinar_h_v(df_medidas)

(         provincia  municipio  estacion  magnitud  punto_muestreo   ano  mes  \
 0               28         79         4         1   28079004_1_38  2001    4
 1               28         79         4         1   28079004_1_38  2001    4
 2               28         79         4         1   28079004_1_38  2001    4
 3               28         79         4         1   28079004_1_38  2001    4
 4               28         79         4         1   28079004_1_38  2001    4
 ...            ...        ...       ...       ...             ...   ...  ...
 2122467         28         92         5         7    28092005_7_8  2025    4
 2122468         28         92         5         8    28092005_8_8  2025    4
 2122469         28         92         5        10  28092005_10_49  2025    4
 2122470         28         92         5        12   28092005_12_8  2025    4
 2122471         28         92         5        14   28092005_14_6  2025    4

          dia   h01 v01  ... h15_v15 h16_v16 h17_v17 h18_v18 h19_v19 h20_v20  \
 0          1  20.0   V  ...   7.0 V   7.0 V   7.0 V   7.0 V   9.0 V   9.0 V
 1          2  17.0   V  ...  12.0 V  12.0 V  11.0 V  11.0 V  12.0 V  12.0 V
 2          3  11.0   V  ...  12.0 V   9.0 V   8.0 V   9.0 V   9.0 V   9.0 V
 3          4   8.0   V  ...  10.0 V  10.0 V   9.0 V  10.0 V  10.0 V  10.0 V
 4          5   8.0   V  ...  10.0 V   9.0 V   8.0 V   8.0 V   9.0 V   9.0 V
 ...      ...   ...  ..  ...     ...     ...     ...     ...     ...     ...
 2122467   30     2   V  ...     2 V     2 V     2 V     2 V     2 V     2 V
 2122468   30     4   V  ...     7 V     8 V     8 V     8 V     7 V     9 V
 2122469   30     7   V  ...    17 V    26 V    25 V    27 V    23 V    20 V
 2122470   30     7   V  ...    10 V    11 V    11 V    11 V    10 V    13 V
 2122471   30    91   V  ...   100 V    99 V    94 V    93 V    94 V    87 V

         h21_v21 h22_v22 h23_v23 h24_v24
 0        11.0 V  18.0 V  27.0 V  34.0 V
 1        14.0 V  15.0 V  13.0 V  11.0 V
 2        10.0 V  11.0 V  10.0 V   9.0 V
 3        10.0 V  10.0 V   9.0 V   8.0 V
 4         9.0 V  11.0 V  13.0 V  14.0 V
 ...         ...     ...     ...     ...
 2122467     2 V     2 V     2 V     3 V
 2122468     8 V    10 V     9 V    12 V
 2122469    28 V    22 V    12 V     6 V
 2122470    11 V    13 V    12 V    17 V
 2122471    79 V    76 V    73 V    67 V

 [2122472 rows x 80 columns],
 ['h01_v01',
  'h02_v02',
  'h03_v03',
  'h04_v04',
  'h05_v05',
  'h06_v06',
  'h07_v07',
  'h08_v08',
  'h09_v09',
  'h10_v10',
  'h11_v11',
  'h12_v12',
  'h13_v13',
  'h14_v14',
  'h15_v15',
  'h16_v16',
  'h17_v17',
  'h18_v18',
  'h19_v19',
  'h20_v20',
  'h21_v21',
  'h22_v22',
  'h23_v23',
  'h24_v24'])

In [14]:
df_medidas_limpio = ft.formato_df(df_medidas)

In [15]:
df_medidas_limpio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50939328 entries, 0 to 50939327
Data columns (total 11 columns):
 #   Column          Dtype
---  ------          -----
 0   provincia       int64
 1   municipio       int64
 2   estacion        int64
 3   magnitud        int64
 4   punto_muestreo  object
 5   fecha           object
 6   hora            object
 7   valor           object
 8   fecha_hora_f    datetime64[ns]
 9   validacion      object
 10  id_medida       object
dtypes: datetime64[ns](1), int64(4), object(6)
memory usage: 4.2+ GB

In [16]:
df_medidas_limpio.to_csv(f"data/transformed/medidas.csv", index=False)